# Generated by Django 3.1.5 on 2021-01-28 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='problem',
            name='topic',
            field=models.CharField(max_length=50),
        ),
    ]
