# Generated by Django 3.1.5 on 2021-02-01 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_problem_technologies'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='identifier',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='topic',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
