# Generated by Django 3.1.5 on 2021-01-28 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('formula', models.CharField(max_length=20)),
                ('compound_type', models.CharField(max_length=20)),
                ('k', models.DecimalField(decimal_places=5, max_digits=7)),
            ],
        ),
    ]
