# Generated by Django 3.1.5 on 2021-01-28 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pHCalculation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compound',
            name='compound_type',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='compound',
            name='formula',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='compound',
            name='k',
            field=models.DecimalField(decimal_places=5, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='compound',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
