# Generated by Django 3.1.5 on 2021-01-28 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pHCalculation', '0002_auto_20210128_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='compound',
            name='value',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='compound',
            name='k',
            field=models.FloatField(null=True),
        ),
    ]
